global:
  smtp_smarthost: 'smtp.qq.com:25'
  smtp_from: '573758972@qq.com'
  smtp_auth_username: '573758972@qq.com'
  smtp_auth_identity: '573758972@qq.com'
  smtp_auth_password: 'clakdvzigydgbbjg'
  smtp_require_tls: false
route:
  group_by:
  - "job"
  receiver: "ops"
receivers:
- name: 'ops'
  email_configs:
  - to: '573758972@qq.com'
