apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "flask-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flask-app.name" . }}
    helm.sh/chart: {{ include "flask-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http
    path: /metrics
  jobLabel: python-app
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flask-app.name" . }}
